# your domain
domain: proxypool-bai.herokuapp.com

speedtest: true

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use web file
  - https://raw.githubusercontent.com/3401797899/proxypool-configs/main/source.yaml
